# Generated by Django 3.2.15 on 2022-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('10', 'Новый'), ('20', 'Распределен'), ('30', 'Приготовление'), ('40', 'Доставка'), ('50', 'Исполнен'), ('90', 'Отменен')], db_index=True, default='10', max_length=2, verbose_name='Статус'),
        ),
    ]
